# Generated by Django 4.2.6 on 2023-10-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(max_length=20)),
                ('student_full_name', models.CharField(max_length=100)),
                ('student_father_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('academic_year', models.IntegerField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
