# Generated by Django 4.2.2 on 2023-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
