# Generated by Django 4.2.2 on 2023-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_generation', '0003_studentdata_tc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
