# Generated by Django 4.2.2 on 2023-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_generation', '0005_alter_studentdata_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='academic_year',
            field=models.CharField(max_length=7),
        ),
    ]
