# Generated by Django 4.2.6 on 2023-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_generation', '0007_alter_studentdata_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
